packages:
  - apps/*
  - packages/*

catalogs:
  ai:
    '@google/genai': ^1.34.0
  backend:
    cookie-parser: ^1.4.7
    cors: ^2.8.5
    express: ^5.2.1
    helmet: ^8.1.0
    jsonwebtoken: ^9.0.3
    morgan: ^1.10.1
    pino: ^10.1.0
    pino-pretty: ^13.1.3
  core:
    dotenv: ^17.2.3
    typescript: ^5.9.3
    zod: ^4.3.5
  infra:
    '@clerk/express': ^1.7.62
    '@upstash/ratelimit': ^2.0.8
    '@upstash/redis': ^1.36.1
  tooling:
    esbuild: ^0.27.2
    eslint: ^9.39.2
    husky: ^9.1.7
    tsc-alias: ^1.8.16
    tsx: ^4.21.0
  types:
    '@types/cookie-parser': ^1.4.8
    '@types/cors': ^2.8.19
    '@types/express': ^5.0.6
    '@types/jsonwebtoken': ^9.0.10
    '@types/morgan': ^1.9.10
    '@types/node': ^25.0.3

cleanupUnusedCatalogs: true
