cleanupUnusedCatalogs: true

packages:
  - apps/*
  - packages/*

catalogs:
  # Core language & validation (shared everywhere)
  core:
    typescript: ^5.9.3
    zod: ^4.3.5
    dotenv: ^17.2.3

  # Backend / API runtime
  backend:
    express: ^5.2.1
    cors: ^2.8.5
    helmet: ^8.1.0
    cookie-parser: ^1.4.7
    jsonwebtoken: ^9.0.3
    morgan: ^1.10.1
    pino: ^10.1.0
    pino-pretty: ^13.1.3

  # Build & runtime tooling
  tooling:
    eslint: ^9.39.2
    tsx: ^4.21.0
    tsc-alias: ^1.8.16
    esbuild: ^0.27.2
    husky: ^9.1.7

  # Type definitions
  types:
    "@types/node": ^25.0.3
    "@types/express": ^5.0.6
    "@types/cors": ^2.8.19
    "@types/morgan": ^1.9.10
    "@types/cookie-parser": ^1.4.8
    "@types/jsonwebtoken": ^9.0.10
    "@types/vscode": ^1.108.1

  # Auth & infra services
  infra:
    "@clerk/express": ^1.7.62
    "@upstash/redis": ^1.36.1
    "@upstash/ratelimit": ^2.0.8

  # AI / external APIs
  ai:
    "@google/genai": ^1.34.0
